// Mocks generated by Mockito 5.3.2 from annotations
// in seg_coursework_app/test/services/helper_classes/firebase_functions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;

import 'firebase_functions_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseFunctionsTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctionsTest extends _i1.Mock
    implements _i2.FirebaseFunctionsTest {
  MockFirebaseFunctionsTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createItem({
    required String? name,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createItem,
          [],
          {
            #name: name,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<dynamic> createCategoryItem({
    required String? name,
    required String? imageUrl,
    required String? categoryId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategoryItem,
          [],
          {
            #name: name,
            #imageUrl: imageUrl,
            #categoryId: categoryId,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<int> getNewCategoryItemRank({required String? categoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewCategoryItemRank,
          [],
          {#categoryId: categoryId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<dynamic> updateItemName({
    required String? itemId,
    required String? newName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemName,
          [],
          {
            #itemId: itemId,
            #newName: newName,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> updateCategoryItemsName({
    required String? itemId,
    required String? newName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryItemsName,
          [],
          {
            #itemId: itemId,
            #newName: newName,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> deleteImageFromCloud({required String? imageUrl}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteImageFromCloud,
          [],
          {#imageUrl: imageUrl},
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<String?> uploadImageToCloud({
    required _i4.File? image,
    required String? itemName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageToCloud,
          [],
          {
            #image: image,
            #itemName: itemName,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<dynamic> updateItemImage({
    required String? itemId,
    required String? newImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemImage,
          [],
          {
            #itemId: itemId,
            #newImageUrl: newImageUrl,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> updateCategoryItemsImage({
    required String? itemId,
    required String? newImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryItemsImage,
          [],
          {
            #itemId: itemId,
            #newImageUrl: newImageUrl,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> deleteCategoryItem({
    required String? categoryId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategoryItem,
          [],
          {
            #categoryId: categoryId,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> getCategoryItemRank({
    required String? categoryId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryItemRank,
          [],
          {
            #categoryId: categoryId,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> updateCategoryRanks({
    required String? categoryId,
    required int? removedRank,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryRanks,
          [],
          {
            #categoryId: categoryId,
            #removedRank: removedRank,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
